### ISSUE TITLE
 Running elf file with error segment fault

### ISSUE THREAD

**Issue by yuxiaoleipeng** [intel/pinball2elf#12]
Hello, I am running the program you provided from https://looppoint.github.io/hpca2023/ The elf file will report an error segment fault
I am runing in OS: Ubuntu 18.04, gcc: 7.5.0, g++: 7.5.0, 'perf' 4.15.18, GNU ld 2.27 : Skylake

**Comment by alenks** [comment]
We expect this behavior as the ELFie may try to access pages that are not captured, typically at the end of the region.

**Comment by yuxiaoleipeng** [comment]
> We expect this behavior as the ELFie may try to access pages that are not captured, typically at the end of the region.

But I tried all elf files in [603.bwaves_s.1]. They all report errors after executing for some time. Is this normal?

**Comment by alenks** [comment]
Yes, try running them with perf to see the user-level cycles/instructions.
```bash
perf stat -e cycles:u,instructions:u <elfie>
```

**Comment by yuxiaoleipeng** [comment]
> Yes, try running them with perf to see the user-level cycles/instructions.
> 
> ```shell
> perf stat -e cycles:u,instructions:u <elfie>
> ```

Thank you very much!
