### ISSUE TITLE
ELFie Generation: Investigate Excessive Disk Usage for Certain Pinballs

### ISSUE THREAD

**Issue by alenks** [intel/pinball2elf#18]
### Description
Opening a new GitHub Issue to track the progress of fixing a bug that occurs while creating ELFies. We notice an unusually large disk usage (creation of a huge temporary file) during the process of generating ELFies for certain pinballs. The link to a reproducer pinball is given here: [x264-r.1_55785_globalr8.tar.gz](https://github.com/user-attachments/files/17796654/x264-r.1_55785_globalr8.tar.gz). The pinball is created using the `-log:fat` option and is re-logged from the whole-program pinball of the SPEC CPU2017 benchmark `525.x264-r.1` using reference inputs. 
### Steps to Reproduce
1. Download the pinball attached
2. Run the ELFie generation script for the pinball
3. Observe the disk space consumption during the process in `/tmp`
### Expected Behavior
The ELFie creation process should utilize reasonable amounts of disk space without generating excessively large temporary files.

**Comment by jinzhaochaliang** [comment]
I submitted PR #19 to resolve this issue.

```shell
$ ll -h ./x264-r.1_55785_globalr8_warmupendPC0x00040a650_warmupendPCCount429801_warmuplength800000039_endPC0x000408659_endPCCount609628_length200000035_multiplier201-000_008_0-06926.perf.elfie 
-rwxrwxr-x 1 root root 161M Nov 20 09:22 ./x264-r.1_55785_globalr8_warmupendPC0x00040a650_warmupendPCCount429801_warmuplength800000039_endPC0x000408659_endPCCount609628_length200000035_multiplier201-000_008_0-06926.perf.elfie*

$ cat st.0.perf.txt 
ROI start: TSC 4093698879704880
Thread start: TSC 4093698946294620
------------------------------------------------
Simulation end: TSC 4093699024770240
        Sim-end-icount 1000120835
hw_cpu_cycles:89293909 hw_instructions:208200984 sw_task_clock:39080799 
------------------------------------------------
Thread end: TSC 4093699025105060
ROI end: TSC 4093699025389120
hw_cpu_cycles:89299161 hw_instructions:208201920 sw_task_clock:39167969
```

**Comment by alenks** [comment]
Closing as [PR#19](https://github.com/intel/pinball2elf/pull/19) resolves the issue.
