### ISSUE TITLE
Huge file under /tmp filled my disk

### ISSUE THREAD

**Issue by haiyang1992** [intel/pinball2elf#3]
While I was running a `perf.sh` script the file `/tmp/p2e-elfie.ZHUzKC` grew to 763G and took over my whole drive. I had to manually delete the file after stopping the script.

**Comment by hgpatil** [comment]
The ELFie generation scripts do use /tmp to 
1. un-compress the input pinball
2. hold temporary object/executable files (there are two calls to '/usr/bin/ld' done that need these files.)

The file you are referring to is one of the temporary object files. Is your pinball itself quite large (especially when uncompressed)? If the pinball has a large memory footprint, all the memory gets put in various object/executable file sections (uncompressed) hence the object file can become large as well.
1. Please check the size of the uncompressed (bunzip2) pinball files, especially the *.text file which has all the region memory pages.
2. The EFLfie generation tool does look for an environment variable "P2E_TEMP" (see how the scripts use that).
     You can set "P2E_TEMP" to point to a large disk and it will be used instead of '/tmp'
3. 763GB does sound unusually big. If the uncompressed pinball is not of similar size, this may be a tool issue which will need to be looked at. First, let us find out if the size of the uncompressed pinball is the reason for the large object file.

**Comment by haiyang1992** [comment]
Thanks Patil for the reply.

I unzipped the pinball files and everything totaled to 90M for that region. I _think_ right now if the disk runs out of space the script will just hang instead of throwing an error.

**Comment by hgpatil** [comment]
The pinball is pretty small hence this looks like a tool issue.
Can you make the pinball available for further debugging? You may send me the location directly to harish.patil@intel.com rather than posting in this forum. Thanks.

**Comment by hgpatil** [comment]
Looked at the test pinballs.
They both end up with a large temporary file 'p2e-elfie.*' filling up the disk. This file is an intermediate ELF object file created by pinball2elf. It, among other things, has one section for each entry in the *.address file in the incoming pinball.
The test pinballs had unusually large address files (3000+ entries). Most entries spanned one or two pages and were quite close (with a page or two worth of hole in-between). This results in an unusually large number of sections in the temporary object file filling up the disk.

Looking at the *.global.log files, both pinballs showed "fat: 0" records indicating '-log:fat' was *not* used while creating the pinballs. With '-log:fat' (which implies '-log:whole_image'), shared library text/static-data pages get captured in the initial memory image (*.txt) and not cause any page-wise injections later. That will avoid the fragmented page entries in the *.address files as seen in the test pinballs. 

In our experiments for the CGO2021 ELFie paper, where pinballs were created with '-log:fat', the *.address files have < 100 entries typically (as opposed to 3000+ seen in the test pinballs). Therefore, re-creating the region pinballs with '-log:fat' might help. '-log:fat' will also ensure the resulting ELFies will run correctly.

Note that, if the region pinballs were carved out from a bigger whole-program pinball, that pinball needs to be 'fat' as well. Please check *.global.log 'fat:' record before proceeding. 

The ELFie generation scripts (scripts/pinball2elf.*.sh) now check that the input pinball is fat and report an error if not.
