### ISSUE TITLE
How to create ELFies that are runnable on a very basic x86 instruction set?

### ISSUE THREAD

**Issue by FJShen** [intel/pinball2elf#6]
I was trying to run ELFies on a CPU with a very basic feature set (e.g. x86_64 + SSE + SSE2 + SSSE3, but no AVX nor XSAVE). The need arose when I wanted to execute the ELFies in a GEM5 full-system mode simulation, and the simulated CPU only supports a limited number of CPU features (as listed by `lscpu`).

I'm using the vallina `pinball2elf.basic.sh` script to do the conversion. Apparently, the current ELFies generated by the tool includes both XSAVE instruction (`xrstor`) and AVX instructions (I see a bunch of instructions from the ELFie that make use of YMM registers - and I know these instructions definitely wasn't there in my application code). 

I was able to hack around the `xrstor` instruction relatively easily - I replaced all occurrences of `xrstor` with the legacy `fxrstor` in the tool's source code as I am confident that my application doesn't use the YMM/ZMM registers anyway. 

However I have trouble getting rid of the AVX instructions. It appears that these AVX instructions are materialized into ELF file as late as the call to `litelfCreateObj()` in the main function - but I have no idea how to turn off these AVX instructions - i.e. substitute them with older instruction sets. Is there a place I can pass in some compiler arguments such as"`-march=core2 -mno-avx <etc. etc.>`" to the toolchain?

**Comment by FJShen** [comment]
After inspecting the disassembly of my statically-linked application executable against the ELFie, I realized i might have overlooked the machine code coming from the standard library. While my application itself does not use any advanced instruction set extension, the standard libraries may do so. My current hypothesis is that the pinball creation tool recorded my application using the AVX-version of functions implemented in the standard library (due to my host machine supporting those features), causing these AVX instructions to show up in my ELFie!

**Comment by hgpatil** [comment]
As you have realized, the AVX registers/code is coming from you binary/pinball. General guidelines:
1. Build your binary with (gcc/g++) -march=x86_64 or -march=core2.
1.1. Adding '-static' will make sure all libraries are linked in statically so no surprises on moving to a different machine.
2. Generate pinball using "sde -nhm" so no new registers are saved in the initial pinball state.
Hope this helps.

**Comment by FJShen** [comment]
Thank you for the suggestion!
