### ISSUE TITLE
Failed to map address of elfies

### ISSUE THREAD

**Issue by meditates** [intel/pinball2elf#9]
Hi, 
I am trying to load the elfies files with gem5 released on https://looppoint.github.io/hpca2023/
but I get the error like this:

src/sim/vma.cc:143: panic: Failed to map file into host address space: Cannot allocate memory
Memory Usage: 3280500 KBytes
Program aborted at tick 620627751

Please give me some suggestions! Thanks a lot!
BTW, I have added vm.max_map_count = 2097152 to /etc/sysctl.conf

Details:
I use the script in https://github.com/gem5-hpca-2023/gem5-tutorial-codespace/blob/master/elfie-refs/elfie.py
with line52 and 53 as: 

elfie = BinaryResource("603.bwaves_s.1/bwaves-s.1_globalr1.sysstate/bwaves-s.1_globalr1.sim.elfie"),
elfie_info = ELFieInfo(PcCountPair(0x4104a6, 1), PcCountPair(0x415031,5680290)) 
 #pccountpair come from "603.bwaves_s.1.config/bwaves-s.1_globalr1.cfg"

My command is gem5/build/X86/gem5.opt elfie-refs/elfie.py

gem5: 2024.Feb
ubuntu 18.0.4
GCC 7.5.0

**Comment by alenks** [comment]
From gem5 sources, `pc` in `PcCountPair` is of type `Addr` (see below), which is used as an alias for `uint64_t`. I think the Python parser may not handle the conversion directly, and hence, it is safer to use the unsigned integer value of the addresses (for example, `int("0x4104a6", 0)` instead of `0x4104a6`) in the configuration script to run ELFies. Let us know if this works.
```cpp
class PcCountPair
{
  private:
    /** The Program Counter address */
    Addr pc;
    /** The count of the Program Counter address */
    int count;
```

**Comment by meditates** [comment]
@alenks No, I still get the same error. I also tried int("0x4104a6", 16)

**Comment by alenks** [comment]
@meditates I just checked the value of `vm.max_map_count` I kept on my setup, which is a much larger number (33554432 in my case). 
Make sure to follow the [link](https://stackoverflow.com/questions/42889241/how-to-increase-vm-max-map-count) to reload the configuration after setting the new value.

**Comment by meditates** [comment]
@alenks I changed the value to your number 33554432. It still aborted with the address problem.

**Comment by alenks** [comment]
> I changed the value to your number 33554432. It still aborted with the address problem.

Did you reload the configuration (see the link shared in the previous comment) before the run?

**Comment by meditates** [comment]
Oh, I forgot to reload the configuration. Now it works! Thanks a lot!

**Comment by alenks** [comment]
Closing as upping `vm.max_map_count` solves the issue.
